"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Profile={id:string;name:string;instagram_username:string|null;posts_per_day:number;posting_times:string[];caption_mode:string;auto_publish:boolean;repeat_when_exhausted:boolean;};
type Item={id:string;source_url:string;title:string|null;status:string;created_at:string;result_url?:string|null;r2_key?:string|null;publish_title?:string|null;publish_description?:string|null;error_message?:string|null;progress?:number;stage?:string|null;};
const STATUS:Record<string,string>={queued:"Na fila",processing:"Processando",available:"Disponível",scheduled:"Agendado",published:"Publicado",failed:"Erro",archived:"Arquivado"};

export default function InfluencerManagerPage(){
 const [profiles,setProfiles]=useState<Profile[]>([]),[selected,setSelected]=useState<Profile|null>(null),[items,setItems]=useState<Item[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[showNew,setShowNew]=useState(false),[name,setName]=useState(""),[instagram,setInstagram]=useState(""),[posts,setPosts]=useState("3"),[url,setUrl]=useState(""),[publishTitle,setPublishTitle]=useState(""),[publishDescription,setPublishDescription]=useState(""),[adding,setAdding]=useState(false),[savingItem,setSavingItem]=useState("");

 async function loadProfiles(){setLoading(true);setError("");try{const r=await fetch("/api/influencer/profiles",{cache:"no-store"}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Não foi possível carregar os perfis.");setProfiles(d.profiles||[]);setSelected(c=>c?(d.profiles||[]).find((p:Profile)=>p.id===c.id)||null:(d.profiles||[])[0]||null);}catch(e){setError(e instanceof Error?e.message:"Erro ao carregar.");}finally{setLoading(false);}}
 async function loadItems(id:string){try{const r=await fetch("/api/influencer/content?profileId="+encodeURIComponent(id),{cache:"no-store"}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Não foi possível carregar a biblioteca.");setItems(d.items||[]);}catch(e){setError(e instanceof Error?e.message:"Erro ao carregar a biblioteca.");}}
 useEffect(()=>{void loadProfiles();},[]);
 useEffect(()=>{if(selected)void loadItems(selected.id);else setItems([]);},[selected?.id]);
 useEffect(()=>{if(!selected||!items.some(i=>i.status==="processing"))return;const timer=window.setInterval(()=>{void Promise.all(items.filter(i=>i.status==="processing").map(async item=>{const r=await fetch("/api/influencer/content/status?id="+item.id,{cache:"no-store"});const d=await r.json().catch(()=>({}));if(r.ok&&d.item)setItems(all=>all.map(x=>x.id===item.id?d.item:x));}));},3000);return()=>window.clearInterval(timer);},[selected?.id,items.map(i=>i.id+":"+i.status).join("|")]);
 async function createProfile(e:FormEvent){e.preventDefault();setSaving(true);setError("");try{const r=await fetch("/api/influencer/profiles",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,instagramUsername:instagram,postsPerDay:Number(posts),postingTimes:[],captionMode:"zh_ja_random"})}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Não foi possível criar o perfil.");setProfiles(p=>[...p,d.profile]);setSelected(d.profile);setName("");setInstagram("");setPosts("3");setShowNew(false);}catch(e){setError(e instanceof Error?e.message:"Erro ao criar perfil.");}finally{setSaving(false);}}
 async function addUrl(e:FormEvent){e.preventDefault();if(!selected||!url.trim())return;setAdding(true);setError("");try{const r=await fetch("/api/influencer/content",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({profileId:selected.id,sourceUrl:url,publishTitle,publishDescription})}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Não foi possível adicionar o vídeo.");setItems(v=>[d.item,...v]);setUrl("");setPublishTitle("");setPublishDescription("");}catch(e){setError(e instanceof Error?e.message:"Erro ao adicionar.");}finally{setAdding(false);}}
 async function saveItem(item:Item,title:string,description:string){setSavingItem(item.id);setError("");try{const r=await fetch("/api/influencer/content",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:item.id,publishTitle:title,publishDescription:description})}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Não foi possível salvar o Reel.");setItems(all=>all.map(x=>x.id===item.id?d.item:x));}catch(e){setError(e instanceof Error?e.message:"Não foi possível salvar o Reel.");}finally{setSavingItem("");}}
 async function updateProfile(patch:Partial<Profile>){if(!selected)return;const r=await fetch("/api/influencer/profiles",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:selected.id,...patch})}),d=await r.json().catch(()=>({}));if(!r.ok){setError(d.error||"Não foi possível salvar.");return;}setSelected(d.profile);setProfiles(all=>all.map(p=>p.id===d.profile.id?d.profile:p));}
 async function removeItem(id:string){const item=items.find(i=>i.id===id);if(!item)return;const message=item.status==="processing"?"Cancelar o processamento deste vídeo?":"Remover este vídeo da biblioteca?";if(!window.confirm(message))return;const r=await fetch("/api/influencer/content?id="+encodeURIComponent(id),{method:"DELETE"});const d=await r.json().catch(()=>({}));if(r.ok)setItems(v=>v.map(i=>i.id===id?{...i,status:item.status==="processing"?"failed":"archived",stage:item.status==="processing"?"canceled":"archived",error_message:d.error||null}:i));else setError(d.error||"Não foi possível remover o conteúdo.");}
 const available=useMemo(()=>items.filter(i=>i.status==="available"||i.status==="queued").length,[items]),days=selected&&selected.posts_per_day?Math.floor(available/selected.posts_per_day):0;
 return <main className="im-page">
  <header className="im-header"><div><a className="im-back" href="/">← Clip Factory</a><span className="im-kicker">INFLUENCER MANAGER</span><h1>Influencer Manager</h1><p>Biblioteca, processamento original e automação de publicação.</p></div><button className="im-primary" onClick={()=>setShowNew(true)}>+ Novo perfil</button></header>
  {error&&<div className="im-alert">{error}</div>}
  {showNew&&<section className="im-card im-form-card"><div className="im-card-head"><div><span className="im-kicker">NOVO PERFIL</span><h2>Criar uma máquina de conteúdo</h2></div><button className="im-ghost" onClick={()=>setShowNew(false)}>Fechar</button></div><form className="im-form" onSubmit={createProfile}><label>Nome do perfil<input value={name} onChange={e=>setName(e.target.value)} placeholder="Memes BR" required /></label><label>Instagram<input value={instagram} onChange={e=>setInstagram(e.target.value)} placeholder="@meuperfil" /></label><label>Reels por dia<input type="number" min="1" max="9" value={posts} onChange={e=>setPosts(e.target.value)} /></label><button className="im-primary" disabled={saving}>{saving?"Criando…":"Criar perfil"}</button></form></section>}
  <section className="im-layout">
   <aside className="im-sidebar"><div className="im-side-head"><span>SEUS PERFIS</span><strong>{profiles.length}</strong></div>{loading?<div className="im-empty">Carregando…</div>:profiles.length===0?<div className="im-empty">Crie seu primeiro perfil para começar.</div>:profiles.map(p=><button key={p.id} className={"im-profile "+(selected?.id===p.id?"active":"")} onClick={()=>setSelected(p)}><span className="im-avatar">{p.name.slice(0,1).toUpperCase()}</span><span><strong>{p.name}</strong><small>{p.instagram_username?"@"+p.instagram_username:"Instagram não conectado"}</small></span><b>{p.posts_per_day}/dia</b></button>)}</aside>
   <section className="im-main">{!selected?<div className="im-card im-empty-main"><strong>Crie um perfil para começar.</strong><span>Depois, adicione URLs de vídeos à biblioteca.</span></div>:<>
    <div className="im-card im-overview"><div><span className="im-kicker">PERFIL ATIVO</span><h2>{selected.name}</h2><p>{selected.instagram_username?"@"+selected.instagram_username:"Conecte um Instagram para publicar automaticamente."}</p></div><div className="im-stats"><div><strong>{items.length}</strong><span>vídeos</span></div><div><strong>{available}</strong><span>em estoque</span></div><div><strong>{days}</strong><span>dias</span></div></div></div>
    <div className="im-card im-add"><div className="im-card-head"><div><span className="im-kicker">BIBLIOTECA</span><h2>Adicionar vídeo</h2><p>O Influencer Manager baixa e armazena o vídeo original. Sem Whisper, tradução, legenda ou corte automático.</p></div></div><form className="im-url-form" onSubmit={addUrl}>
      <input value={url} onChange={e=>setUrl(e.target.value)} placeholder="Cole a URL do YouTube" required />
      <input value={publishTitle} onChange={e=>setPublishTitle(e.target.value)} placeholder="Nome do Reel que será publicado" />
      <textarea value={publishDescription} onChange={e=>setPublishDescription(e.target.value)} placeholder="Descrição do Reel que será publicado" rows={3} />
      <button className="im-primary" disabled={adding}>{adding?"Iniciando…":"Adicionar vídeo"}</button>
    </form></div>
    <div className="im-card im-settings"><div className="im-card-head"><div><span className="im-kicker">AUTOMAÇÃO</span><h2>Publicação</h2><p>Esta configuração controla se o perfil poderá entrar na fila automática.</p></div><strong className={"im-status "+(selected.auto_publish?"available":"archived")}>{selected.auto_publish?"ATIVA":"DESLIGADA"}</strong></div><div className="im-settings-grid"><label>Reels por dia<select value={selected.posts_per_day} onChange={e=>void updateProfile({posts_per_day:Number(e.target.value)})}>{[1,2,3,4,5,6,7,8,9].map(n=><option key={n}>{n}</option>)}</select></label><label>Descrição<select value={selected.caption_mode} onChange={e=>void updateProfile({caption_mode:e.target.value})}><option value="zh_ja_random">Chinês + Japonês aleatório</option><option value="zh_random">Chinês</option><option value="ja_random">Japonês</option><option value="custom">Banco personalizado</option></select></label><label className="im-check"><input type="checkbox" checked={selected.auto_publish} onChange={e=>void updateProfile({auto_publish:e.target.checked})}/><span>Permitir publicação automática</span></label><label className="im-check"><input type="checkbox" checked={selected.repeat_when_exhausted} onChange={e=>void updateProfile({repeat_when_exhausted:e.target.checked})}/><span>Repetir quando a biblioteca acabar</span></label></div><div className="im-times"><span className="im-kicker">HORÁRIOS DIÁRIOS</span><div className="im-time-grid">{Array.from({length:selected.posts_per_day},(_,i)=><label key={i}>Post {i+1}<input type="time" value={selected.posting_times?.[i]||["09:00","11:30","14:00","16:30","19:00","21:30","23:00","08:00","12:00"][i]} onChange={e=>{const times=[...(selected.posting_times||[])];while(times.length<selected.posts_per_day)times.push("");times[i]=e.target.value;void updateProfile({posting_times:times});}} /></label>)}</div><small>Os horários ficam salvos no perfil. A fila automática será ativada na etapa de publicação.</small></div><div className="im-auto-note">{selected.auto_publish?"Automação autorizada no perfil. A publicação real só será agendada quando a fila de publicação estiver habilitada.":"Nenhuma publicação automática será criada enquanto estiver desligada."}</div></div>
    <div className="im-card im-library"><div className="im-card-head"><div><span className="im-kicker">CONTEÚDO</span><h2>Biblioteca</h2></div><span className="im-count">{items.length}</span></div>{items.length===0?<div className="im-empty">Nenhum vídeo cadastrado.</div>:<div className="im-items">{items.map(item=><article className="im-item" key={item.id}><div className="im-item-main"><strong>{item.title||"Vídeo sem título"}</strong><span>{item.source_url}</span>{item.status==="processing"&&<div className="im-progress"><div><span style={{width:(item.progress||5)+"%"}} /></div><small>{item.progress||5}% · {item.stage==="download"?"Baixando vídeo":item.stage==="upload"?"Enviando para o R2":"Preparando worker"}</small></div>}{item.error_message&&<small className="im-error-text">{item.error_message}</small>}{item.result_url&&<video className="im-video-preview" src={item.result_url} controls preload="metadata" />} {item.status!=="processing"&&item.status!=="archived"&&<div className="im-reel-copy"><label>Nome do Reel<input defaultValue={item.publish_title||item.title||""} onBlur={e=>void saveItem(item,e.target.value,item.publish_description||"")} /></label><label>Descrição<textarea defaultValue={item.publish_description||""} rows={3} onBlur={e=>void saveItem(item,item.publish_title||item.title||"",e.target.value)} /></label>{savingItem===item.id&&<small>Salvando…</small>}</div>}</div><div className="im-item-actions"><span className={"im-status "+item.status}>{STATUS[item.status]||item.status}</span>{item.status==="processing"?<button className="im-ghost" onClick={()=>void removeItem(item.id)}>Cancelar</button>:item.result_url?<a className="im-ghost" href={item.result_url} target="_blank" rel="noreferrer">Abrir vídeo</a>:null}{item.status!=="processing"&&<button className="im-ghost" onClick={()=>void removeItem(item.id)}>Excluir</button>}</div></article>)}</div>}</div>
   </>}</section>
  </section>
 </main>;
}