"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Profile = { id:string; name:string; instagram_username:string|null; posts_per_day:number; posting_times:string[]; caption_mode:string; auto_publish:boolean; repeat_when_exhausted:boolean; };
type Item = { id:string; source_url:string; title:string|null; status:string; created_at:string; };
const STATUS:Record<string,string>={queued:"Na fila",processing:"Processando",available:"Disponível",scheduled:"Agendado",published:"Publicado",failed:"Erro",archived:"Arquivado"};

export default function InfluencerManagerPage(){
 const [profiles,setProfiles]=useState<Profile[]>([]),[selected,setSelected]=useState<Profile|null>(null),[items,setItems]=useState<Item[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[showNew,setShowNew]=useState(false),[name,setName]=useState(""),[instagram,setInstagram]=useState(""),[posts,setPosts]=useState("3"),[url,setUrl]=useState(""),[adding,setAdding]=useState(false);
 async function loadProfiles(){setLoading(true);setError("");try{const r=await fetch("/api/influencer/profiles",{cache:"no-store"}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Não foi possível carregar os perfis.");setProfiles(d.profiles||[]);setSelected(c=>c?(d.profiles||[]).find((p:Profile)=>p.id===c.id)||null:(d.profiles||[])[0]||null);}catch(e){setError(e instanceof Error?e.message:"Erro ao carregar.");}finally{setLoading(false);}}
 async function loadItems(id:string){try{const r=await fetch("/api/influencer/content?profileId="+encodeURIComponent(id),{cache:"no-store"}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Não foi possível carregar a biblioteca.");setItems(d.items||[]);}catch(e){setError(e instanceof Error?e.message:"Erro ao carregar a biblioteca.");}}
 useEffect(()=>{void loadProfiles();},[]);
 useEffect(()=>{if(selected)void loadItems(selected.id);else setItems([]);},[selected?.id]);
 useEffect(()=>{
  if(!selected || !items.some(item=>item.status==="processing")) return;
  const timer=window.setInterval(()=>void loadItems(selected.id),5000);
  return()=>window.clearInterval(timer);
 },[selected?.id,items.some(item=>item.status==="processing")]);
 async function createProfile(e:FormEvent){e.preventDefault();setSaving(true);setError("");try{const r=await fetch("/api/influencer/profiles",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,instagramUsername:instagram,postsPerDay:Number(posts),postingTimes:[],captionMode:"zh_ja_random"})}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Não foi possível criar o perfil.");setProfiles(p=>[...p,d.profile]);setSelected(d.profile);setName("");setInstagram("");setPosts("3");setShowNew(false);}catch(e){setError(e instanceof Error?e.message:"Erro ao criar perfil.");}finally{setSaving(false);}}
 async function addUrl(e:FormEvent){e.preventDefault();if(!selected||!url.trim())return;setAdding(true);setError("");try{const r=await fetch("/api/influencer/content",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({profileId:selected.id,sourceUrl:url})}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Não foi possível adicionar o vídeo.");setItems(v=>[d.item,...v]);setUrl("");}catch(e){setError(e instanceof Error?e.message:"Erro ao adicionar.");}finally{setAdding(false);}}
 async function updateProfile(patch:Partial<Profile>){if(!selected)return;const r=await fetch("/api/influencer/profiles",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:selected.id,...patch})}),d=await r.json().catch(()=>({}));if(!r.ok){setError(d.error||"Não foi possível salvar.");return;}setSelected(d.profile);setProfiles(all=>all.map(p=>p.id===d.profile.id?d.profile:p));}
 async function removeItem(id:string){if(!window.confirm("Remover este vídeo da biblioteca?"))return;const r=await fetch("/api/influencer/content?id="+encodeURIComponent(id),{method:"DELETE"});if(r.ok)setItems(v=>v.filter(i=>i.id!==id));}
 const available=useMemo(()=>items.filter(i=>i.status==="available"||i.status==="queued").length,[items]),days=selected&&selected.posts_per_day?Math.floor(available/selected.posts_per_day):0;
 return <main className="im-page">
  <header className="im-header"><div><a className="im-back" href="/">← Clip Factory</a><span className="im-kicker">INFLUENCER MANAGER</span><h1>Perfis de conteúdo.</h1><p>Organize bibliotecas, horários e publicação automática em um único lugar.</p></div><button className="im-primary" onClick={()=>setShowNew(true)}>+ Novo perfil</button></header>
  {error&&<div className="im-alert">{error}</div>}
  {showNew&&<section className="im-card im-form-card"><div className="im-card-head"><div><span className="im-kicker">NOVO PERFIL</span><h2>Criar uma máquina de conteúdo</h2></div><button className="im-ghost" onClick={()=>setShowNew(false)}>Fechar</button></div><form className="im-form" onSubmit={createProfile}><label>Nome do perfil<input value={name} onChange={e=>setName(e.target.value)} placeholder="Memes BR" required /></label><label>Instagram<input value={instagram} onChange={e=>setInstagram(e.target.value)} placeholder="@meuperfil" /></label><label>Reels por dia<input type="number" min="1" max="9" value={posts} onChange={e=>setPosts(e.target.value)} /></label><button className="im-primary" disabled={saving}>{saving?"Criando…":"Criar perfil"}</button></form></section>}
  <section className="im-layout">
   <aside className="im-sidebar"><div className="im-side-head"><span>SEUS PERFIS</span><strong>{profiles.length}</strong></div>{loading?<div className="im-empty">Carregando…</div>:profiles.length===0?<div className="im-empty">Crie seu primeiro perfil para começar.</div>:profiles.map(p=><button key={p.id} className={"im-profile "+(selected?.id===p.id?"active":"")} onClick={()=>setSelected(p)}><span className="im-avatar">{p.name.slice(0,1).toUpperCase()}</span><span><strong>{p.name}</strong><small>{p.instagram_username?"@"+p.instagram_username:"Instagram não conectado"}</small></span><b>{p.posts_per_day}/dia</b></button>)}</aside>
   <section className="im-main">{!selected?<div className="im-card im-empty-main"><strong>Crie um perfil para começar.</strong><span>Depois, basta adicionar URLs de vídeos à biblioteca.</span></div>:<>
    <div className="im-card im-overview"><div><span className="im-kicker">PERFIL ATIVO</span><h2>{selected.name}</h2><p>{selected.instagram_username?"@"+selected.instagram_username:"Conecte um Instagram para publicar automaticamente."}</p></div><div className="im-stats"><div><strong>{items.length}</strong><span>vídeos</span></div><div><strong>{available}</strong><span>em estoque</span></div><div><strong>{days}</strong><span>dias</span></div></div></div>
    <div className="im-card im-add"><div className="im-card-head"><div><span className="im-kicker">BIBLIOTECA</span><h2>Adicionar conteúdo</h2><p>Cole a URL do vídeo. O Clip Factory processa uma vez e deixa o resultado pronto na biblioteca.</p></div></div><form className="im-url-form" onSubmit={addUrl}><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://youtube.com/watch?v=..." /><button className="im-primary" disabled={adding}>{adding?"Adicionando…":"Adicionar vídeo"}</button></form></div>
    <div className="im-card im-settings"><div className="im-card-head"><div><span className="im-kicker">AUTOMAÇÃO</span><h2>Configuração do perfil</h2></div></div><div className="im-settings-grid"><label>Reels por dia<select value={selected.posts_per_day} onChange={e=>void updateProfile({posts_per_day:Number(e.target.value)})}>{[1,2,3,4,5,6,7,8,9].map(n=><option key={n}>{n}</option>)}</select></label><label>Descrição<select value={selected.caption_mode} onChange={e=>void updateProfile({caption_mode:e.target.value})}><option value="zh_ja_random">Chinês + Japonês aleatório</option><option value="zh_random">Chinês</option><option value="ja_random">Japonês</option><option value="custom">Banco personalizado</option></select></label><label className="im-check"><input type="checkbox" checked={selected.auto_publish} onChange={e=>void updateProfile({auto_publish:e.target.checked})}/><span>Publicação automática</span></label><label className="im-check"><input type="checkbox" checked={selected.repeat_when_exhausted} onChange={e=>void updateProfile({repeat_when_exhausted:e.target.checked})}/><span>Repetir quando a biblioteca acabar</span></label></div><div className="im-coming">Horários fixos e capa padrão entram na próxima etapa do módulo.</div></div>
    <div className="im-card im-library"><div className="im-card-head"><div><span className="im-kicker">CONTEÚDO</span><h2>Biblioteca</h2></div><span className="im-count">{items.length}</span></div>{items.length===0?<div className="im-empty">Nenhum vídeo cadastrado.</div>:<div className="im-items">{items.map(item=><article className="im-item" key={item.id}><div><strong>{item.title||"Vídeo sem título"}</strong><span>{item.source_url}</span></div><div className="im-item-actions"><span className={"im-status "+item.status}>{STATUS[item.status]||item.status}</span>{item.result_url&&<a className="im-ghost" href={item.result_url} target="_blank" rel="noreferrer">Preview</a>}<button className="im-ghost" onClick={()=>void removeItem(item.id)}>Remover</button></div></article>)}</div>}</div>
   </>}</section>
  </section>
 </main>;
}
